import re

cap5 = """
# 5. Marco teórico y conceptos clave

Para comprender la solución tecnológica propuesta y el diseño del *pipeline* geoespacial, es imperativo asentar exhaustivamente los pilares científicos sobre los que se sustenta la arquitectura del proyecto. Este marco teórico aborda tanto la física óptica de la observación satelital como los fundamentos matemáticos del aprendizaje profundo convolucional.

## 5.1. Datos espaciales: Sentinel-2 y el espectro electromagnético

El satélite Sentinel-2, perteneciente al programa Copernicus de la Agencia Espacial Europea (ESA), provee imágenes multiespectrales de alta resolución. Para optimizar la capacidad de discriminación del modelo de inteligencia artificial desarrollado en este proyecto, no se procesa una composición RGB tradicional o la totalidad de las 13 bandas nativas del sensor MSI (*MultiSpectral Instrument*). En su lugar, se ha aplicado una severa reducción de dimensionalidad mediante *Feature Engineering*, alimentando a la red neuronal con un tensor espacial optimizado de 7 canales simultáneos. Esta selección estratégica previene la saturación de memoria de la unidad de procesamiento gráfico (OOM - *Out of Memory*) al tiempo que maximiza la varianza de la información introducida:

1. **Espectro visible (Bandas B02, B03 y B04 - Resolución 10m):** Correspondientes a las longitudes de onda del Azul (490 nm), Verde (560 nm) y Rojo (665 nm). Estas bandas capturan las texturas físicas superficiales, los verdaderos colores de las cubiertas terrestres, la morfología urbana y las sombras topográficas proyectadas por el relieve escarpado. Su alta resolución espacial es indispensable para delinear los bordes exactos de las nubes pequeñas (cúmulos).
2. **Infrarrojo Cercano o NIR (Banda B08 - Resolución 10m):** Operando a 842 nm, es el espectro crítico para identificar la reflectancia de la clorofila vegetal y, por ende, las masas forestales. De igual forma, los cuerpos de agua profunda absorben intensamente esta radiación infrarroja, presentando firmas espectrales muy oscuras (cercanas al cero absoluto) que facilitan su delimitación matemática.
3. **Infrarrojo de Onda Corta o SWIR (Bandas B11 y B12 - Resolución 20m):** Operando a 1610 nm y 2190 nm respectivamente, estas bandas son el fundamento físico que permite resolver la ambigüedad espectral objeto de esta tesis: la confusión entre nube y nieve. Físicamente, las nubes (cristales de hielo en suspensión o vapor de agua) presentan una alta reflectancia en el SWIR, apareciendo brillantes. Por el contrario, la nieve consolidada sobre el terreno absorbe fuertemente el SWIR, oscureciéndose drásticamente. Esta divergencia óptica es el vector principal de decisión para el algoritmo.
4. **NDSI (*Normalized Difference Snow Index*):** Como séptimo canal de entrada, se ha inyectado un índice matemático derivado pre-calculado: `(B03 - B11) / (B03 + B11)`. La inyección de este canal adicional no es trivial; su propósito es forzar matemáticamente a la red neuronal a prestar atención explícita a la física de la nieve desde la primera época de entrenamiento (*Epoch 0*). En lugar de esperar a que la red deduzca la relación entre el Verde y el SWIR tras millones de iteraciones de descenso de gradiente, se le proporciona la frontera de decisión empírica resuelta, facilitando y acelerando exponencialmente la convergencia del modelo.

## 5.2. Inteligencia Artificial: La Arquitectura U-Net

Mientras que los algoritmos paramétricos tradicionales (como el Sen2Cor nativo de la ESA) evalúan la radiometría del terreno píxel a píxel mediante árboles de decisión rígidos y estáticos, ignorando por completo el contexto vecinal de la imagen, este proyecto fundamenta su salto cualitativo en el **Aprendizaje Profundo (*Deep Learning*)**, concretamente en el subcampo de la **Visión Artificial (*Computer Vision*)**. 

La arquitectura convolucional seleccionada para gobernar el núcleo predictivo del sistema es la **U-Net** (*Ronneberger, Fischer & Brox, 2015*). Esta topología se ha implementado desde cero (*From Scratch*) utilizando el *framework* **PyTorch**, estándar absoluto de la industria en el cálculo tensorial por aceleración de hardware (CUDA).

### 5.2.1. Teoría de Funcionamiento
La arquitectura U-Net es la red neuronal convolucional (CNN) *de facto* para tareas de **segmentación semántica espacial**. Esto implica que el sistema no se limita a realizar una clasificación binaria de la imagen (e.g. dictaminar "aquí hay nubes"), sino que calcula una inferencia matemática independiente para cada píxel individual de la matriz, adjudicándole una clase y dibujando sus contornos morfológicos exactos. Su nomenclatura deriva de su estructura simétrica en forma de "U", la cual consta de tres engranajes fundamentales:

1. **El Encoder (Ruta de Contracción o Bajada):** A medida que el tensor satelital (de dimensiones 512x512 píxeles) ingresa en la red, el modelo aplica sucesivas operaciones de convolución matemática y funciones de activación no lineal (ReLU), seguidas de reducciones agresivas de tamaño espacial mediante capas de *Max Pooling*. En este descenso hacia la base de la "U", el tensor pierde resolución espacial drásticamente, pero multiplica su profundidad geométrica (canales de características). Conceptualmente, el Encoder extrae la semántica abstracta de la imagen, aprendiendo el **"QUÉ"** (la firma espectral que diferencia una sombra orográfica de un lago, o una nube de la nieve alpina).
2. **El Decoder (Ruta de Expansión o Subida):** Representa el vector ascendente de la arquitectura. Toma la información matricial hipercomprimida (el espacio latente profundo) y la expande progresivamente mediante convoluciones transpuestas (*Up-convolutions*) hasta recuperar las dimensiones espaciales originales de 512x512 píxeles. Su propósito iterativo es proyectar el conocimiento semántico aprendido de vuelta sobre el espacio geográfico bidimensional; en otras palabras, el Decoder resuelve el **"DÓNDE"** (las coordenadas topológicas exactas de los elementos detectados).
3. **Las Skip Connections (Puentes de Resolución):** La descompresión aislada de un tensor altamente contraído generaría, por defecto, una salida semántica de bordes extremadamente difusos y borrosos. Para erradicar este problema topológico, la U-Net instaura "puentes horizontales" que concatenan directamente los mapas de características de alta resolución del Encoder con las capas de reconstrucción correspondientes en el Decoder. Estas conexiones residuales rescatan las texturas espaciales finas originales y las inyectan en las etapas finales, permitiendo a la red trazar fronteras de clasificación con precisión milimétrica (a nivel de píxel), un requisito indispensable para cartografiar límites de nieves perpetuas o líneas de costa.

### 5.2.2. Diseño Arquitectónico y Tratamiento del Espacio Latente (*Data Shapes*)
El flujo de tensores a través de la red neuronal (*Forward Pass*) se somete a estrictas reglas de dimensionalidad y precisión de punto flotante para garantizar la estabilidad matemática del descenso de gradiente:

- **Entradas (*Inputs - X*):** Su forma matricial topológica es `(Batch_Size, 7, 512, 512)`. Un aspecto crítico de la optimización del *pipeline* geoespacial es la gestión del almacenamiento en disco. Los cientos de miles de tensores se guardan físicamente en formato `Float16` (Media Precisión). Esta directiva de Ingeniería de Datos reduce la huella de almacenamiento un 50% y acelera drásticamente la latencia de lectura (I/O). Sin embargo, al inyectarse en el modelo para el entrenamiento activo, los tensores se transforman obligatoriamente en memoria a `Float32` (Precisión Simple). Si el algoritmo de *Backpropagation* (retropropagación del error) utilizara `Float16`, carecería de la profundidad decimal necesaria para almacenar las actualizaciones microscópicas de los gradientes matemáticos, provocando que los pesos sinápticos se redondearan a cero (*Underflow*) y colapsando el aprendizaje de la red.
- **Salidas (*Outputs - Y_pred*):** El tensor resultante emitido por la última capa convolucional de la red (Decoder) presenta una forma `(Batch_Size, 6, 512, 512)`. Estos 6 canales paralelos representan los *Logits* crudos o puntuaciones matemáticas no normalizadas correspondientes a la taxonomía de las 6 Clases Maestras del proyecto: 0 (NoData / Descarte), 1 (Suelo Útil), 2 (Nube), 3 (Sombra de Nube), 4 (Nieve), 5 (Masa de Agua).
- **Activación y Colapso Espacial:** Para materializar el mapa 2D final, una función matemática `Softmax` evalúa el vector de profundidad de 6 posiciones de cada píxel, normalizando las puntuaciones en probabilidades absolutas (que suman 1.0). El píxel asume irrevocablemente el valor de la clase (0 a 5) que ostente la probabilidad máxima estadística, generando la máscara final de segmentación.

### 5.2.3. Justificación Crítica: Programación "From Scratch" frente a *Transfer Learning*
Pese a la hegemonía actual del uso de redes neuronales pre-entrenadas adaptadas a tareas específicas (*Transfer Learning*), la dirección arquitectónica de este TFB determinó programar e inicializar los pesos sinápticos de la U-Net íntegramente desde cero (*From Scratch*). Esta drástica decisión se ampara en cuatro vulnerabilidades detectadas en los modelos públicos heredables:

1. **Incompatibilidad de Entradas Físicas:** Los modelos convolucionales de la comunidad científica (como Sen2Earth) están rígidamente diseñados en sus capas de entrada para ingerir la totalidad de las 10 o 13 bandas satelitales del formato SAFE nativo. Nuestra estrategia exige la ingesta de un tensor mutado de 7 canales (donde se han purgado las bandas de aerosoles atmosféricos y se ha inyectado sintéticamente el índice NDSI). Amputar la capa inicial de una red pre-entrenada para forzar la aceptación de 7 canales corrompe inmediatamente los pesos matemáticos subyacentes transferidos, invalidando su inteligencia previa.
2. **Incompatibilidad de la Taxonomía de Salidas:** Las redes comerciales de teledetección suelen exportar una topología binaria (1 = Nube, 0 = Terreno). Este proyecto orquesta una segmentación profunda de 6 Clases Maestras diseñadas específicamente para resolver la paradoja orográfica de Cataluña (separando nieve alpina, sombra de nube y agua marítima). Modificar simultáneamente la estructura de la cabeza (*Head*) y de la entrada (*Input*) de una red importada desestabiliza las capas intermedias, provocando el olvido catastrófico de los patrones espaciales.
3. **Erradicación del Sesgo Geográfico:** El *Transfer Learning* surgió como panacea ante la escasez de datos. Paradójicamente, la ejecución prolongada del *pipeline* ETL de este trabajo ha generado una Verdad Terreno masiva compuesta por más de 8.000 tensores hiper-específicos de la topografía catalana (Pirineos, Delta del Ebro, Llanura de Lleida). Iniciar el entrenamiento desde un lienzo en blanco asegura que la red extraiga las variables geomorfológicas intrínsecas a nuestra área de estudio, inmunizándola contra los sesgos atmosféricos y luminosos heredados de redes pre-entrenadas en paisajes globales dispares (ej. desiertos o selvas tropicales).
4. **Generalización Demostrada:** La literatura académica subraya que, disponiendo de una biblioteca de tensores de alta calidad (*Ground Truth* auditado por humanos), el diseño "From Scratch" en arquitecturas CNN puras supera consistentemente a los híbridos pre-entrenados, acoplándose simbióticamente a las necesidades del caso de uso empresarial.

### 5.2.4. Evaluación Empírica y Función de Pérdida
El control direccional del entrenamiento neuronal (descenso de gradiente) exige la formulación matemática de métricas de castigo severas para guiar el aprendizaje.

- **Función de Pérdida - `CrossEntropyLoss` (Estrategia de Enmascarado Geográfico):** Durante el entrenamiento, la red se somete a la pérdida de Entropía Cruzada. Un factor crucial de ingeniería ha sido la inyección algorítmica del parámetro `ignore_index=0`. Al recortar en cuadrículas un paso satelital irregular, emergen multitud de píxeles "muertos" (triángulos negros fuera del barrido orbital del Sentinel-2, codificados como clase 0). Si la función de pérdida procesara estos píxeles irrelevantes, la IA intentaría encontrar patrones espectrales en la nada, desviando su vector de convergencia. El parámetro de exclusión impone matemáticamente a la red que el 100% de la penalización (o recompensa) de actualización de pesos provenga exclusivamente de las 5 clases geográficas útiles.
- **Métrica Científica - *Intersection over Union* (IoU):** En la monitorización satelital, evaluar un modelo mediante su Precisión Global (*Overall Accuracy*) constituye una negligencia metodológica debido al extremo desbalanceo geográfico. En un día soleado, el 95% de la superficie catalana es Suelo Útil, y apenas un 5% es Nieve en el Alto Pirineo. Una IA perezosa que siempre pronosticara "Suelo" obtendría una puntuación de precisión del 95%, siendo tácticamente inservible. Para demoler este espejismo estadístico, el proyecto emplea el índice IoU (Coeficiente Jaccard) para cada clase de forma aislada. El IoU cruza geométricamente el área inferida por la IA con el polígono real editado manualmente, castigando de forma implacable la mínima desviación en los falsos positivos y la omisión en los falsos negativos.

## 5.3. Estrategia de Datos y Decisiones Arquitectónicas

La concepción de un *pipeline* geoespacial masivo implica tomar decisiones troncales que impactan irrevocablemente la viabilidad técnica y computacional del despliegue en la nube. A continuación, se justifican analíticamente las posturas científicas adoptadas:

### 5.3.1. Nivel de Procesamiento: Ingesta L1C frente a L2A
- **Decisión Arquitectónica:** Aislar y descargar exclusivamente las imágenes en bruto L1C (*Top of Atmosphere*).
- **Justificación:** Las formaciones nubosas habitan físicamente en las capas altas y medias de la troposfera. Someter el tensor satelital a las pesadas correcciones atmosféricas L2A (*Bottom of Atmosphere*) carece de fundamentación física para los píxeles atmosféricos. Más grave aún: el producto L2A oficial hereda los errores históricos del procesador Sen2Cor de la ESA (que clasifica cumbres nevadas como cirros). Entrenar la U-Net con datos alterados (L2A) supondría inyectar un sesgo algorítmico estructural irresoluble. Ingerir los reflectores inmaculados L1C permite a las redes neuronales derivar características atmosféricas vírgenes, asumiendo el estándar tecnológico de modelos punteros como *s2cloudless* o *Fmask*.

### 5.3.2. Unificación Orbital (R008 frente a R051)
- **Decisión Arquitectónica:** Consolidar el entrenamiento en un único modelo universal, indiferente a la órbita relativa del satélite.
- **Justificación:** El satélite Sentinel-2 cruza la península ibérica mediante dos pasadas orbitales diametralmente opuestas (R008 y R051), las cuales inciden sobre el territorio en días distintos. Esta variabilidad provee ángulos acimutales y de observación solar heterogéneos. En lugar de desarrollar un modelo por órbita, al agrupar ambas pasadas en un espacio latente unificado se desencadena un proceso orgánico de *Data Augmentation*. La U-Net se ve forzada a volverse invariante a la rotación orbital y a las variaciones de iluminación topográfica. Fragmentar el sistema duplicaría los costes de inferencia *Serverless* y mermaría la capacidad de generalización del sistema.

### 5.3.3. Generalización Geográfica (Norte vs Sur)
- **Decisión Arquitectónica:** Desplegar una única matriz neuronal para cubrir la disparidad topográfica completa de Cataluña.
- **Justificación:** Dividir artificialmente el desarrollo en un modelo de Alta Montaña (Pirineos) y otro Litoral (Mediterráneo) fracturaría la arquitectura del software. Si una nevada histórica o una granizada extrema (e.g. borrasca Filomena) cubriera de blanco las cotas bajas del Sur, el modelo litoral (que jamás ha procesado tensores de nieve) colapsaría, catalogando la superficie como nubosidad de alta densidad. Inyectar simultáneamente los "casos extremos" (sombras escarpadas nórdicas frente al *Sun Glint* de las costas y arrozales del Delta del Ebro) garantiza la **Generalización del Dominio**, dotando al modelo de la robustez necesaria para soportar anomalías climáticas fuera de la distribución estándar (*Out-of-Distribution Data*).

### 5.3.4. Estrategia de Recorte (*Tiling* Directo vs *Mosaicking*)
- **Decisión Arquitectónica:** Ejecutar el troceado espacial matricial (teselas de 512x512 píxeles) directamente sobre el gránulo geográfico nativo (MGRS), descartando radicalmente la pre-fusión (*Mosaicking*).
- **Justificación:** Unificar gránulos vecinos procedentes de órbitas y días diferentes antes del recorte provoca la aparición de "costuras" espaciales (*seamlines*), con gradientes de iluminación antinaturales y bordes aserrados en las formaciones de nubes y nieve. Las redes neuronales convolucionales son devoradoras de patrones de alta frecuencia; ingerir estas cicatrices artificiales generaría filtros matemáticos aberrantes, aprendiendo geometría que no existe en el mundo real. Preservar el barrido puro orbital L1C y fragmentarlo iterativamente salvaguarda la coherencia topológica y evita desbordamientos masivos de la memoria RAM.

### 5.3.5. Modelos de Elevación Digital (El Descarte del DEM)
- **Decisión Arquitectónica:** Construir el tensor de entrada confiando estrictamente en fotometría 2D, extirpando cualquier inyección de Modelos Digitales de Elevaciones 3D.
- **Justificación:** Si bien el DEM es la solución matemática ideal para que un modelo comprenda la profundidad de un valle escarpado y prediga las sombras orográficas, su incorporación violaría los principios de rendimiento (*Green Computing*) y agilidad del *pipeline* web. Re-proyectar y alinear métricamente las matrices raster de elevación (resoluciones dispares de 5m del ICGC frente a los 10m/20m del satélite) para cada píxel de Cataluña multiplicaría exponencialmente la complejidad algorítmica y el tiempo de inferencia *offline*. Se ha optado por delegar todo el peso de la discriminación física en las bandas SWIR y el índice NDSI, asumiendo la ineludible pérdida de precisión en umbrías profundas a favor de una arquitectura cien veces más veloz, liviana y exportable a otras regiones planetarias carentes de cartografía 3D de alta definición.

### 5.3.6. El Rechazo al Análisis Multitemporal (*Single-Image Prediction*)
- **Decisión Arquitectónica:** Anular el uso de imágenes pasadas libres de nubes para comparar con el estado actual; todo el peso predictivo recae sobre el tensor satelital en el momento absoluto de la captura (*Single-Image*).
- **Justificación:** La geografía de estudio presenta un elevado dinamismo fenológico y antrópico. En los macizos alpinos la nieve es episódica; en el tejido agrícola del Delta del Ebro, las llanuras inundables pasan de ser masas oscuras de agua a extensos mantos verdes brillantes de arroz en cuestión de semanas. Una red neuronal basada en comparativa multitemporal interpretaría estos contrastes espectrales repentinos como gruesas barreras de nubes. La arquitectura *Single-Image* fuerza a la Inteligencia Artificial a deducir el estado atmosférico evaluando exclusivamente las interacciones radiométricas instantáneas, garantizando un índice nulo de falsos positivos frente a los cambios de las estaciones del año.

### 5.3.7. Omisión de Máscaras Vectoriales Estáticas de Agua
- **Decisión Arquitectónica:** Extirpar de la arquitectura la inyección cartográfica de lagos y ríos (e.g. archivos GeoJSON del ACA).
- **Justificación:** En ciclos plurianuales de sequía extrema (como el padecido en el embalse de Sau), un mapa vectorial estático inyectaría la clasificación categórica de "Masa de agua profunda", cuando el sensor satelital óptico en tiempo real detecta claramente terreno estéril y rocoso altamente reflectante. Esta brutal disonancia matricial destrozaría los gradientes de retropropagación del modelo. El agua pura actúa físicamente como un agujero negro radiométrico en las frecuencias del Infrarrojo Cercano (NIR). La U-Net capacitada absorbe esta propiedad óptica de los canales físicos al instante, demostrando que depender de bases de datos cartográficas inmovilistas resulta obsoleto frente al dinamismo de una inferencia matemática *on-the-fly*.
"""

# Inject into 009.md
with open("/home/a.lopez.g/Documents/trabajos/node_2/web_basic_project/011_tfb/000_doc_tfb/000_entrega_03_antonio_lopez_009.md", "r", encoding="utf-8") as f:
    doc9 = f.read()

c5_start = doc9.find("# 5. Marco teórico y conceptos clave")
c6_start = doc9.find("# 6. Metodología aplicada")

doc9 = doc9[:c5_start] + cap5 + "\n\n" + doc9[c6_start:]

with open("/home/a.lopez.g/Documents/trabajos/node_2/web_basic_project/011_tfb/000_doc_tfb/000_entrega_03_antonio_lopez_009.md", "w", encoding="utf-8") as f:
    f.write(doc9)

print("Chapter 5 heavily expanded and injected successfully!")
